api_platform:
    title: 'Jeux de r√¥le'
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    defaults:
        stateless: true
        pagination_items_per_page: 10
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 100
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
