lexik_jwt_authentication:
    token_ttl: 3600
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    api_platform:
        check_path: /api/login/check
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization

        cookie:
            enabled: true
            name: BEARER

    set_cookies:
        BEARER:
            samesite: lax
            path: /
            domain: null
            secure: true
            httpOnly: true

    remove_token_from_body_when_cookies_used: true
